# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries


# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine cython
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*

# python setup.py sdist bdist_wheel

# name: Upload Python Package

# on:
#   release:
#     types: [created]

# jobs:
#   Linux-build:
#     runs-on: ubuntu-latest
#     env:
#       TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#       TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#     steps:
#       - uses: actions/checkout@v2

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           apt-get install -y libffi-dev
#           pip install setuptools wheel twine cython

#       - name: build and upload manylinux wheels
#         uses: Niraj-Kamdar/manylinux-wheel-builder@master

#   Matrix-build:
#     runs-on: ${{ matrix.os }}
#     env:
#       TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#       TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#     strategy:
#       matrix:
#         os: [macos-latest, windows-latest]
#         python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install setuptools wheel twine cython
#       - name: build wheel
#         run: |
#           pip install wheel
#           python setup.py sdist bdist_wheel
#       - name: upload wheel
#         run: |
#           pip install twine
#           twine upload dist/*
#         continue-on-error: true
